#pragma config(Sensor, in2,    rightLiftPot,   sensorPotentiometer)
#pragma config(Sensor, in3,    leftLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in4,    clawLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in5,    leftMobilePot,  sensorPotentiometer)
#pragma config(Sensor, in6,    rightMobilePot, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightMobile,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftMobile,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           clawLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightDrive,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float joyStickCurve(float value) {
	if (value < 0) {
		return -1 * exp(0.03790648643687201 * -value);
	}
	return exp(0.03790648643687201 * value);
}


task main()
{
	while(true) {
		// Arcade Controls
		int c3 =  -(vexRT[Ch3]);
		int j3 = joyStickCurve(c3);
		int c1 = vexRT[Ch1];
		int j1 = joyStickCurve(c1);

		if(((c1>20||c1<-20)||(c3>20||c3<-20))){
			motor[rightDrive] = (j3 + j1);
			motor[leftDrive] = (j1 - j3);
		}else{
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
		}

		// Mobile Lift

		if (vexRT[Btn6D] || vexRT[Btn5DXmtr2]) {
			motor[leftMobile] = 100;
			motor[rightMobile] = 100;
		} else if (vexRT[Btn5D] || vexRT[Btn5UXmtr2]) {
			motor[leftMobile] = -100;
			motor[rightMobile] = -100;
		} else {
			motor[leftMobile] = 0;
			motor[rightMobile] = 0;
		}

		// Lift
		if (abs(vexRT[Ch3Xmtr2]) > 20) {
			float j3 = joyStickCurve(vexRT[Ch3Xmtr2]);
			motor[leftLift] = j3;
			motor[rightLift] = j3;
		} else {
			motor[leftLift] = 0;
			motor[rightLift] = 0;
		}

		// Claw Lift
		if (abs(vexRT[Ch2Xmtr2]) > 20) {
			float j2 = joyStickCurve(vexRT[Ch2Xmtr2]);
			motor[clawLift] = j2;
		} else {
			motor[clawLift] = 0;
		}

		// Claw
		if (vexRT[Btn6UXmtr2]) {
			motor[claw] = -100;
		} else if (vexRT[Btn6DXmtr2]) {
			motor[claw] = 100;
		} else {
			motor[claw] = 0;
		}


	}

}
