#pragma config(Sensor, in2,    ClawLift1,      sensorPotentiometer)
#pragma config(Sensor, in3,    LiftRight,      sensorPotentiometer)
#pragma config(Sensor, in5,    LiftLeft,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftMobile,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LeftLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ClawLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightMobile,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightDrive,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool shouldWait = false;


float wheelRadius = 2;
float turnRadius = 6.7;

void openLift() {
	// Extending to placing cone height
	while(SensorValue[LiftRight]<4090&&SensorValue[LiftLeft]<4075){
		motor[RightLift] = 70;
		motor[LeftLift] = 70;
	}
	motor[RightLift] = 0;
	motor[LeftLift] = 0;
}

void stack() {
	/*
	// Lower Claw Lift to Stack Position
	while(SensorValue[ClawLift1]<1300){
		motor[ClawLift] = 30;
	}
	motor[ClawLift] = 0;

	wait(0.5);
	*/

	// Lower Lift to Stack Position
	while(SensorValue[LiftRight]>3400&&SensorValue[LiftLeft]>3500){
		motor[RightLift] = -70;
		motor[LeftLift] = -70;
	}
	motor[RightLift] = 0;
	motor[LeftLift] = 0;

}

void openClawLift() {
		// Lower Claw Lift to Stack Position
	SensorValue[ClawLift1]=4000;
	while(SensorValue[ClawLift1]>1300){
		motor[ClawLift] = -60;
	}
	motor[ClawLift] = 0;
}

void dropCone() {
	motor[Claw] = -60;
	wait(0.5);
	openClawLift();
	motor[Claw] = 0;
}

void closeLift() {
	while(SensorValue[LiftRight]>3350&&SensorValue[LiftLeft]>3425){
		motor[RightLift] = -70;
		motor[LeftLift] = -70;
	}
	motor[RightLift] = 0;
	motor[LeftLift] = 0;
}

void openMobile() {
	motor[LeftMobile] = 80;
	motor[RightMobile] = 80;
	wait(1);
	motor[LeftMobile] = 0;
	motor[RightMobile] = 0;
}

void closeMobile(bool hasCone) {
	motor[LeftMobile] = -80;
	motor[RightMobile] = -80;
	if (hasCone) {
		wait(1.5);
	} else {
		wait(1.2);
	}
	motor[LeftMobile] = 0;
	motor[RightMobile] = 0;
}

float rotsFor(float degrees) {
	float wheelCircumference = 2 * PI * wheelRadius;
	float turnCircumference = 2 * PI * turnRadius;

	float degRatio = abs(degrees)/360;
	float turnDist = degRatio * turnCircumference;
	return turnDist / wheelCircumference;
}

float inchesToRots(float inches) {
	float wheelCircumference = 2 * PI * wheelRadius;
	return abs(inches) / wheelCircumference;
}

// ----------TURNING-----------

float turnDegrees = 0;
float turnSpeed = 0;



task turnME() {
	float rots = rotsFor(turnDegrees);
	float rotDegrees = rots * 360;

	SensorValue[LeftEncoder] = 0;
	SensorValue[RightEncoder] = 0;

	if (degrees > 0) {
		motor[LeftDrive] = turnSpeed;
		motor[RightDrive] = -turnSpeed;
	} else {
		motor[LeftDrive] = -turnSpeed;
		motor[RightDrive] = turnSpeed;
	}

	while (abs(SensorValue[LeftEncoder]) < rotDegrees || abs(SensorValue[RightEncoder]) < rotDegrees) {
		if (abs(SensorValue[LeftEncoder]) >= rotDegrees && abs(SensorValue[RightEncoder]) >= rotDegrees) {
			motor[LeftDrive] = 0;
			motor[RightDrive] = 0;
		}
	}

	shouldWait = false;
	EndTimeSlice();
}

void turn(float deg, float speed){
	turnDegrees = deg;
	turnSpeed = speed;
	startTask(turnME);
}

// -------- MOVING ---------

float moveInches = 0;
float moveSpeed = 0;

task moveME() {
	float rots = inchesToRots(moveInches);
	float adjustment = 1;
	float rotDegrees = rots * 360* adjustment;

	SensorValue[LeftEncoder] = 0;
	SensorValue[RightEncoder] = 0;

	if (moveInches > 0) {
		motor[LeftDrive] = moveSpeed;
		motor[RightDrive] = moveSpeed;
	} else {
		motor[LeftDrive] = -moveSpeed;
		motor[RightDrive] = -moveSpeed;
	}

	while (abs(SensorValue[LeftEncoder]) < rotDegrees || abs(SensorValue[RightEncoder]) < rotDegrees) {
		if (abs(SensorValue[LeftEncoder]) >= rotDegrees && abs(SensorValue[RightEncoder]) >= rotDegrees) {
			motor[LeftDrive] = 0;
			motor[RightDrive] = 0;
		}
	}

	shouldWait = false;
	EndTimeSlice();
}

void move(float inches, float speed) {
	moveInches = inches;
	moveSpeed = speed;
	startTask(moveME);
}

task main(){
	//turn(-90, 60);
	//move(20,60);
	//openMobile();
	//wait(1);
	//closeMobile(true);
	/*
	openLift();
	wait(1);
	stack();
	wait(1);
	dropCone();
	*/

	// Program Start
	// Open Lift
	openLift();
	openClawLift();
	openMobile();

	shouldWait = true;
	move(45, 90);
	while(shouldWait) {}

	wait(0.5);

	shouldWait = true;
	turn(-160, 90); // <- Asynchronous
	closeMobile(true);
	while(shouldWait) {}

	shouldWait = true;
	move(45,90); // <- Asynchronous

	stack();
	wait(1);
	dropCone();
	while(shouldWait) {}

	openMobile();

	wait(1);

	shouldWait = true;
	move(-15,90);
	closeMobile(false);
	while(shouldWait) {}


}
