#pragma config(Sensor, in2,    clawLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in3,    leftLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in4,    rightLiftPot,   sensorPotentiometer)
#pragma config(Sensor, in5,    leftMobilePot,  sensorPotentiometer)
#pragma config(Sensor, in6,    rightMobilePot, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMobile,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftMobile,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           clawLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightDrive,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		// Arcade Controls
		int c3 = -(vexRT[Ch3]);
		int c1 = vexRT[Ch1];

		if(((c1>20||c1<-20)||(c3>20||c3<-20))){
			motor[rightDrive] = (c3 + c1);
			motor[leftDrive] = (c1 - c3);
		}else{
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
		}

		// Mobile Lift

		if (vexRT[Btn6D]) {
			motor[leftMobile] = 100;
			motor[rightMobile] = 100;
		} else if (vexRT[Btn5D]) {
			motor[leftMobile] = -100;
			motor[rightMobile] = -100;
		} else {
			motor[leftMobile] = 0;
			motor[rightMobile] = 0;
		}
	}


}
