#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mobile,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftChainBar,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightChainBar, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
			// Movement
			if (abs(vexRT[Ch3]) > 60) {
				motor[leftDrive] = vexRT[Ch3];
			} else {
				motor[leftDrive] = 0;
			}

			if (abs(vexRT[Ch2]) > 60) {
				motor[rightDrive] = vexRT[Ch2];
			} else {
				motor[rightDrive] = 0;
			}

			if (vexRT[Btn6D]) {
				motor[mobile] = 120;
			} else if (vexRT[Btn5D]) {
				motor[mobile] = -120;
			} else {
				motor[mobile] = 0;
			}
	}
}
